//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contract.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shartnoma maker.
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyingisi.
        /// </summary>
        internal static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaxsiy parolni kiriting.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaxsiy parolni qayta kiriting.
        /// </summary>
        internal static string EnterPasswordAgain {
            get {
                return ResourceManager.GetString("EnterPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxsus kodni kiriting.
        /// </summary>
        internal static string EnterSpecialCode {
            get {
                return ResourceManager.GetString("EnterSpecialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISTALGAN JOYDA 
        /// SHARTNOMA TUZISH.
        /// </summary>
        internal static string Intro1_1 {
            get {
                return ResourceManager.GetString("Intro1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofisda bo&apos;lmang, bug&apos;galterni kutmang.  
        ///O&apos;zingizga qulay vaqtda, qulay joyda 
        ///shartnomalarni tuzing..
        /// </summary>
        internal static string Intro1_2 {
            get {
                return ResourceManager.GetString("Intro1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAYYOR SHARTNOMANI ONSON 
        /// JO&apos;NATISH.
        /// </summary>
        internal static string Intro2_1 {
            get {
                return ResourceManager.GetString("Intro2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shartnomalarni qo&apos;lda olib borish 
        /// shart emas. Ularni istalgan messenjer 
        /// orqali PDF formatida yuvorish..
        /// </summary>
        internal static string Intro2_2 {
            get {
                return ResourceManager.GetString("Intro2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QISQA MUDDATDA 
        /// SHARTNOMA TUZISH.
        /// </summary>
        internal static string Intro3_1 {
            get {
                return ResourceManager.GetString("Intro3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endi shartnoma tuzish ko&apos;p vaqt olmaydi. 
        /// Shunchaki asosiy ma&apos;lumotlarni 
        /// to&apos;ldiring va shartnoma tayyor..
        /// </summary>
        internal static string Intro3_2 {
            get {
                return ResourceManager.GetString("Intro3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QULAY SHABLONLAR 
        /// YARATISH.
        /// </summary>
        internal static string Intro4_1 {
            get {
                return ResourceManager.GetString("Intro4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shartnoma tuzish uchu o&apos;z huquqlar, 
        /// talablar va imidjingizga mos 
        /// shablonlarni yaratib, 
        /// ulardan onson foydalaning..
        /// </summary>
        internal static string Intro4_2 {
            get {
                return ResourceManager.GetString("Intro4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOYDA VA ZARARLARNI 
        /// TAHLIL QILISH.
        /// </summary>
        internal static string LoginInfo1_1 {
            get {
                return ResourceManager.GetString("LoginInfo1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcha bajarilgan amalyotlar bo&apos;yicha 
        /// kirim-chimlarni foyda va zararlarga 
        /// ajrating.
        /// </summary>
        internal static string LoginInfo1_2 {
            get {
                return ResourceManager.GetString("LoginInfo1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tizimga kirish.
        /// </summary>
        internal static string LoginSystem {
            get {
                return ResourceManager.GetString("LoginSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telfon raqamingizni kiriting.
        /// </summary>
        internal static string M_EnterPhoneNumber {
            get {
                return ResourceManager.GetString("M_EnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoki.
        /// </summary>
        internal static string M_Or {
            get {
                return ResourceManager.GetString("M_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ro&apos;yxatdan o&apos;ting.
        /// </summary>
        internal static string M_SignUp {
            get {
                return ResourceManager.GetString("M_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assalomu alaykum hurmatli mijoz!.
        /// </summary>
        internal static string M_Title1 {
            get {
                return ResourceManager.GetString("M_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tizimdan foydalanish uchun avtorizasiya qiling..
        /// </summary>
        internal static string M_Title2 {
            get {
                return ResourceManager.GetString("M_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayni damda tadiqlanmagan shartnomalar mavjud emas..
        /// </summary>
        internal static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iltimos, o&apos;zingizga qulay bo&apos;lgan murakkab parolni kiriting va unutmang. Bu parol, siz tizimga kirishingiz vaqtida kerak bo&apos;ladi..
        /// </summary>
        internal static string PasswordDescription {
            get {
                return ResourceManager.GetString("PasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodni qayta yuborish.
        /// </summary>
        internal static string SendSpecialCode {
            get {
                return ResourceManager.GetString("SendSpecialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biz sizga telegram tarmog&apos;i orqali maxsus kod yuvoramiz. Shu bois, telfon raqam telegram tarmog&apos;iga ulangan bo&apos;lishi lozim..
        /// </summary>
        internal static string SignUpDescription {
            get {
                return ResourceManager.GetString("SignUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telfon raqamingizni kiriting.
        /// </summary>
        internal static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O&apos;tkazib yuborish.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram tarmog&apos;i orqali siz ko&apos;rsatgan telfon raqamiga yuborilgan maxsus kodni kiriting..
        /// </summary>
        internal static string SpecialCodeDescription {
            get {
                return ResourceManager.GetString("SpecialCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kutish vaqti.
        /// </summary>
        internal static string WaitingTime {
            get {
                return ResourceManager.GetString("WaitingTime", resourceCulture);
            }
        }
    }
}
