//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contract.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the program.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the software.
        /// </summary>
        internal static string AboutSoftware {
            get {
                return ResourceManager.GetString("AboutSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountant Name.
        /// </summary>
        internal static string AccountantName {
            get {
                return ResourceManager.GetString("AccountantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Big Bottom Clause.
        /// </summary>
        internal static string AddBigBottomClause {
            get {
                return ResourceManager.GetString("AddBigBottomClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Big Up Clause.
        /// </summary>
        internal static string AddBigUpClause {
            get {
                return ResourceManager.GetString("AddBigUpClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Clause.
        /// </summary>
        internal static string AddClause {
            get {
                return ResourceManager.GetString("AddClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Copy.
        /// </summary>
        internal static string AddCopy {
            get {
                return ResourceManager.GetString("AddCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Empty.
        /// </summary>
        internal static string AddEmpty {
            get {
                return ResourceManager.GetString("AddEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Customer.
        /// </summary>
        internal static string AddNewCustomer {
            get {
                return ResourceManager.GetString("AddNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Of Company.
        /// </summary>
        internal static string AddressOfCompany {
            get {
                return ResourceManager.GetString("AddressOfCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Of Contract.
        /// </summary>
        internal static string AddressOfContract {
            get {
                return ResourceManager.GetString("AddressOfContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Small Bottom Clause.
        /// </summary>
        internal static string AddSmallBottomClause {
            get {
                return ResourceManager.GetString("AddSmallBottomClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Small Up Clause.
        /// </summary>
        internal static string AddSmallUpClause {
            get {
                return ResourceManager.GetString("AddSmallUpClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        internal static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check agree box to proceed.
        /// </summary>
        internal static string AgreeMessage {
            get {
                return ResourceManager.GetString("AgreeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Contracts.
        /// </summary>
        internal static string AllContracts {
            get {
                return ResourceManager.GetString("AllContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Of  VAT.
        /// </summary>
        internal static string AmountOfQQS {
            get {
                return ResourceManager.GetString("AmountOfQQS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Contracts.
        /// </summary>
        internal static string ApprovedContracts1 {
            get {
                return ResourceManager.GetString("ApprovedContracts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved
        ///Contracts.
        /// </summary>
        internal static string ApprovedContracts2 {
            get {
                return ResourceManager.GetString("ApprovedContracts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to approve the contract?.
        /// </summary>
        internal static string ApproveMessage {
            get {
                return ResourceManager.GetString("ApproveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Maker.
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a tax payer?.
        /// </summary>
        internal static string AreYou_QQS_Payer {
            get {
                return ResourceManager.GetString("AreYou_QQS_Payer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto login.
        /// </summary>
        internal static string AutoLogin {
            get {
                return ResourceManager.GetString("AutoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you select automatic login, you will be logged in automatically and will not have to enter password and username every time at the log in screen..
        /// </summary>
        internal static string AutoLogMessage {
            get {
                return ResourceManager.GetString("AutoLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Code.
        /// </summary>
        internal static string BankCode {
            get {
                return ResourceManager.GetString("BankCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string ButtonFinished {
            get {
                return ResourceManager.GetString("ButtonFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel has been failed..
        /// </summary>
        internal static string Cancel_Message_1 {
            get {
                return ResourceManager.GetString("Cancel_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a comment.
        /// </summary>
        internal static string Cancel_Message_2 {
            get {
                return ResourceManager.GetString("Cancel_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract has been canceled..
        /// </summary>
        internal static string Cancel_Message_3 {
            get {
                return ResourceManager.GetString("Cancel_Message_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled Contracts.
        /// </summary>
        internal static string CanceledContracts {
            get {
                return ResourceManager.GetString("CanceledContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the basis for terminating contracts.
        /// </summary>
        internal static string CancellationComment {
            get {
                return ResourceManager.GetString("CancellationComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel Termination of Contract No..
        /// </summary>
        internal static string CancelTerminationOfContractNo {
            get {
                return ResourceManager.GetString("CancelTerminationOfContractNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use your tin number..
        /// </summary>
        internal static string CannotUseYourStirNumber {
            get {
                return ResourceManager.GetString("CannotUseYourStirNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change account password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check ID.
        /// </summary>
        internal static string CheckID {
            get {
                return ResourceManager.GetString("CheckID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Accountant Name.
        /// </summary>
        internal static string ChiefAccountantName {
            get {
                return ResourceManager.GetString("ChiefAccountantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Name.
        /// </summary>
        internal static string ChiefName {
            get {
                return ResourceManager.GetString("ChiefName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the contract number format..
        /// </summary>
        internal static string ChooseContractNumberFormat {
            get {
                return ResourceManager.GetString("ChooseContractNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an image.
        /// </summary>
        internal static string ChooseImage {
            get {
                return ResourceManager.GetString("ChooseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clauses.
        /// </summary>
        internal static string Clauses {
            get {
                return ResourceManager.GetString("Clauses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        internal static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to clean the window?.
        /// </summary>
        internal static string CleanMessage {
            get {
                return ResourceManager.GetString("CleanMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Contractor Name.
        /// </summary>
        internal static string CompanyContractorName {
            get {
                return ResourceManager.GetString("CompanyContractorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Logo.
        /// </summary>
        internal static string CompanyLogo {
            get {
                return ResourceManager.GetString("CompanyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIN of the enterprise.
        /// </summary>
        internal static string CompanySTIRi {
            get {
                return ResourceManager.GetString("CompanySTIRi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm By Special Code.
        /// </summary>
        internal static string ConfirmationBySpecialCode {
            get {
                return ResourceManager.GetString("ConfirmationBySpecialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm By Digital Signature.
        /// </summary>
        internal static string ConfirmByDigitalSignature {
            get {
                return ResourceManager.GetString("ConfirmByDigitalSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract number format is exist. .
        /// </summary>
        internal static string ContractFormatExist {
            get {
                return ResourceManager.GetString("ContractFormatExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Number.
        /// </summary>
        internal static string ContractNumber {
            get {
                return ResourceManager.GetString("ContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Number Sequence.
        /// </summary>
        internal static string ContractNumberSequence {
            get {
                return ResourceManager.GetString("ContractNumberSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Price.
        /// </summary>
        internal static string ContractPrice {
            get {
                return ResourceManager.GetString("ContractPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Templates.
        /// </summary>
        internal static string ContractTemplates {
            get {
                return ResourceManager.GetString("ContractTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contragent.
        /// </summary>
        internal static string Contragent {
            get {
                return ResourceManager.GetString("Contragent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contragent phone number.
        /// </summary>
        internal static string ContragentPhoneNumber {
            get {
                return ResourceManager.GetString("ContragentPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the contract..
        /// </summary>
        internal static string CouldNotCreateContract {
            get {
                return ResourceManager.GetString("CouldNotCreateContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find..
        /// </summary>
        internal static string CouldNotFind {
            get {
                return ResourceManager.GetString("CouldNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the contragent phone number!.
        /// </summary>
        internal static string CouldNotFindContragent {
            get {
                return ResourceManager.GetString("CouldNotFindContragent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counsel Name.
        /// </summary>
        internal static string CounselName {
            get {
                return ResourceManager.GetString("CounselName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Contract.
        /// </summary>
        internal static string CreateContract {
            get {
                return ResourceManager.GetString("CreateContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Contract Number.
        /// </summary>
        internal static string CreateContractNumber {
            get {
                return ResourceManager.GetString("CreateContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Contract Template.
        /// </summary>
        internal static string CreatingContractTemplate {
            get {
                return ResourceManager.GetString("CreatingContractTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company TIN.
        /// </summary>
        internal static string CTRiOfCompany {
            get {
                return ResourceManager.GetString("CTRiOfCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract currency.
        /// </summary>
        internal static string CurrencyOfTheContract {
            get {
                return ResourceManager.GetString("CurrencyOfTheContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Contracts.
        /// </summary>
        internal static string CurrentContracts {
            get {
                return ResourceManager.GetString("CurrentContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        internal static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D1.
        /// </summary>
        internal static string D1 {
            get {
                return ResourceManager.GetString("D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Contract.
        /// </summary>
        internal static string DateOfContract {
            get {
                return ResourceManager.GetString("DateOfContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Text of the day).
        /// </summary>
        internal static string DayText {
            get {
                return ResourceManager.GetString("DayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Clause.
        /// </summary>
        internal static string DeleteClause {
            get {
                return ResourceManager.GetString("DeleteClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete?.
        /// </summary>
        internal static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device does not currently support this feature!.
        /// </summary>
        internal static string DeviceMessage1 {
            get {
                return ResourceManager.GetString("DeviceMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you forgot password?.
        /// </summary>
        internal static string DidYouForgotPassword {
            get {
                return ResourceManager.GetString("DidYouForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal documents.
        /// </summary>
        internal static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Account Password.
        /// </summary>
        internal static string EditAccountPassword {
            get {
                return ResourceManager.GetString("EditAccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All cells can be filled with arbitrary characters.
        /// </summary>
        internal static string EditContractNumberTitle1 {
            get {
                return ResourceManager.GetString("EditContractNumberTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty cells are not counted.
        /// </summary>
        internal static string EditContractNumberTitle2 {
            get {
                return ResourceManager.GetString("EditContractNumberTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay attention to the correctness of the identification marks entered in the cells and that they are filled in according to the instructions. These numbers remain an integral part of the created contracts..
        /// </summary>
        internal static string EditContractNumberTitle3 {
            get {
                return ResourceManager.GetString("EditContractNumberTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of a digit sequence is 12 characters..
        /// </summary>
        internal static string EditContractNumberTitle4 {
            get {
                return ResourceManager.GetString("EditContractNumberTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit contract templates.
        /// </summary>
        internal static string EditContractTemplate {
            get {
                return ResourceManager.GetString("EditContractTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        internal static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing Contract Number.
        /// </summary>
        internal static string EditingContractNumber {
            get {
                return ResourceManager.GetString("EditingContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Personal Details.
        /// </summary>
        internal static string EditPersonalDetails {
            get {
                return ResourceManager.GetString("EditPersonalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Requisite Information.
        /// </summary>
        internal static string EditRequisiteInformation {
            get {
                return ResourceManager.GetString("EditRequisiteInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Address Of Company.
        /// </summary>
        internal static string EnterAddressOfCompany {
            get {
                return ResourceManager.GetString("EnterAddressOfCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Bank Code.
        /// </summary>
        internal static string EnterBankCode {
            get {
                return ResourceManager.GetString("EnterBankCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Company Name.
        /// </summary>
        internal static string EnterCompanyName {
            get {
                return ResourceManager.GetString("EnterCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the TIN of company..
        /// </summary>
        internal static string EnterCompanyStir {
            get {
                return ResourceManager.GetString("EnterCompanyStir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Current Password.
        /// </summary>
        internal static string EnterCurrentPassword {
            get {
                return ResourceManager.GetString("EnterCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter id or phone number.
        /// </summary>
        internal static string EnterID_or_PhoneNumber {
            get {
                return ResourceManager.GetString("EnterID_or_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name of Bank.
        /// </summary>
        internal static string EnterNameOfBank {
            get {
                return ResourceManager.GetString("EnterNameOfBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new ID.
        /// </summary>
        internal static string EnterNewID {
            get {
                return ResourceManager.GetString("EnterNewID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter New Password.
        /// </summary>
        internal static string EnterNewPassword {
            get {
                return ResourceManager.GetString("EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter your personal password.
        /// </summary>
        internal static string EnterPasswordAgain {
            get {
                return ResourceManager.GetString("EnterPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your signature..
        /// </summary>
        internal static string EnterSignature {
            get {
                return ResourceManager.GetString("EnterSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Special Code.
        /// </summary>
        internal static string EnterSpecialCode {
            get {
                return ResourceManager.GetString("EnterSpecialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty space: May be alphabet or digit..
        /// </summary>
        internal static string ExYourChoose {
            get {
                return ResourceManager.GetString("ExYourChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field cannot be empty.
        /// </summary>
        internal static string FieldEmpty {
            get {
                return ResourceManager.GetString("FieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay attention to the accuracy of the details. This information will be used as the details of the company when concluding an agreement..
        /// </summary>
        internal static string FillInfoDescription {
            get {
                return ResourceManager.GetString("FillInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your company information..
        /// </summary>
        internal static string FillInfoTitle {
            get {
                return ResourceManager.GetString("FillInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find ID.
        /// </summary>
        internal static string FindID {
            get {
                return ResourceManager.GetString("FindID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Password.
        /// </summary>
        internal static string FindPassword {
            get {
                return ResourceManager.GetString("FindPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will send you a temporary password and you can use it, but once you login then you should change your password based on the temporal password..
        /// </summary>
        internal static string FindPasswordDescription {
            get {
                return ResourceManager.GetString("FindPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First And Last Name.
        /// </summary>
        internal static string FirstAndLastName {
            get {
                return ResourceManager.GetString("FirstAndLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods.
        /// </summary>
        internal static string Goods {
            get {
                return ResourceManager.GetString("Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification Marks.
        /// </summary>
        internal static string IdentificationMarks {
            get {
                return ResourceManager.GetString("IdentificationMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Number.
        /// </summary>
        internal static string IDNumber {
            get {
                return ResourceManager.GetString("IDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay attention to the accuracy of the details. This information will be used as the details of the company when concluding an agreement..
        /// </summary>
        internal static string Info1 {
            get {
                return ResourceManager.GetString("Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The price is per unit of measure.
        /// </summary>
        internal static string Info2 {
            get {
                return ResourceManager.GetString("Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay attention to the reliability of service information. This information is used as the main work performed by the contractor in the contract..
        /// </summary>
        internal static string Info3 {
            get {
                return ResourceManager.GetString("Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add contract service details.
        /// </summary>
        internal static string Info4 {
            get {
                return ResourceManager.GetString("Info4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add contractor information.
        /// </summary>
        internal static string Info5 {
            get {
                return ResourceManager.GetString("Info5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service information of the contract.
        /// </summary>
        internal static string Info6 {
            get {
                return ResourceManager.GetString("Info6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of contractors.
        /// </summary>
        internal static string Info7 {
            get {
                return ResourceManager.GetString("Info7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a complex password that is comfortable for you and remember it. This password is required when logging in.
        /// </summary>
        internal static string Info8 {
            get {
                return ResourceManager.GetString("Info8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a complex password that is comfortable for you and remember it. This password is required when logging in.
        /// </summary>
        internal static string Info9 {
            get {
                return ResourceManager.GetString("Info9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no canceled contracts at this time..
        /// </summary>
        internal static string InformMessage1 {
            get {
                return ResourceManager.GetString("InformMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You missed the waiting time. Please click the Resend Code button..
        /// </summary>
        internal static string InformMessage2 {
            get {
                return ResourceManager.GetString("InformMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no unconfirmed contracts at this time..
        /// </summary>
        internal static string InformMessage3 {
            get {
                return ResourceManager.GetString("InformMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no current contracts..
        /// </summary>
        internal static string InformMessage4 {
            get {
                return ResourceManager.GetString("InformMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no list of contract templates available at this time..
        /// </summary>
        internal static string InformMessage5 {
            get {
                return ResourceManager.GetString("InformMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently no contract number sequence listing available..
        /// </summary>
        internal static string InformMessage6 {
            get {
                return ResourceManager.GetString("InformMessage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No customer list available at this time..
        /// </summary>
        internal static string InformMessage7 {
            get {
                return ResourceManager.GetString("InformMessage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        internal static string Internet {
            get {
                return ResourceManager.GetString("Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN A CONTRACT ANYWHERE.
        /// </summary>
        internal static string Intro1_1 {
            get {
                return ResourceManager.GetString("Intro1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No need to be in the office, no need to wait for an accountant. Sign contracts at a convenient time for you, in a convenient place..
        /// </summary>
        internal static string Intro1_2 {
            get {
                return ResourceManager.GetString("Intro1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONVENIENT SENDING THE READY AGREEMENT.
        /// </summary>
        internal static string Intro2_1 {
            get {
                return ResourceManager.GetString("Intro2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts do not need to be manually transferred. Send them in PDF format via any messenger..
        /// </summary>
        internal static string Intro2_2 {
            get {
                return ResourceManager.GetString("Intro2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conclude a short-term contract.
        /// </summary>
        internal static string Intro3_1 {
            get {
                return ResourceManager.GetString("Intro3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now the conclusion of the contract does not take much time. Just fill in the basic information and the contract is ready..
        /// </summary>
        internal static string Intro3_2 {
            get {
                return ResourceManager.GetString("Intro3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE EASY TEMPLATES.
        /// </summary>
        internal static string Intro4_1 {
            get {
                return ResourceManager.GetString("Intro4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and easily use templates that match your rights, requirements and image to conclude a contract..
        /// </summary>
        internal static string Intro4_2 {
            get {
                return ResourceManager.GetString("Intro4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is an accountant provided?.
        /// </summary>
        internal static string IsCounterProvided {
            get {
                return ResourceManager.GetString("IsCounterProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Legal Counsel provided?.
        /// </summary>
        internal static string IsLegalCounselProvided {
            get {
                return ResourceManager.GetString("IsLegalCounselProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Consultant Name.
        /// </summary>
        internal static string LegalConsultantName {
            get {
                return ResourceManager.GetString("LegalConsultantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Customers.
        /// </summary>
        internal static string ListOfCustomers {
            get {
                return ResourceManager.GetString("ListOfCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the phone number or password..
        /// </summary>
        internal static string Login_Message_1 {
            get {
                return ResourceManager.GetString("Login_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROFIT AND LOSS ANALYSIS.
        /// </summary>
        internal static string LoginInfo1_1 {
            get {
                return ResourceManager.GetString("LoginInfo1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide all actions by profit and loss across all completed transactions.
        /// </summary>
        internal static string LoginInfo1_2 {
            get {
                return ResourceManager.GetString("LoginInfo1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login System.
        /// </summary>
        internal static string LoginSystem {
            get {
                return ResourceManager.GetString("LoginSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string Logotip {
            get {
                return ResourceManager.GetString("Logotip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Phone Number.
        /// </summary>
        internal static string M_EnterPhoneNumber {
            get {
                return ResourceManager.GetString("M_EnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string M_Or {
            get {
                return ResourceManager.GetString("M_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string M_SignUp {
            get {
                return ResourceManager.GetString("M_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello dear client!.
        /// </summary>
        internal static string M_Title1 {
            get {
                return ResourceManager.GetString("M_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to use the system..
        /// </summary>
        internal static string M_Title2 {
            get {
                return ResourceManager.GetString("M_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M1.
        /// </summary>
        internal static string M1 {
            get {
                return ResourceManager.GetString("M1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main page.
        /// </summary>
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        internal static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no unconfirmed contracts..
        /// </summary>
        internal static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no unconfirmed contracts..
        /// </summary>
        internal static string Message2 {
            get {
                return ResourceManager.GetString("Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no active contracts..
        /// </summary>
        internal static string Message3 {
            get {
                return ResourceManager.GetString("Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no canceled contracts..
        /// </summary>
        internal static string Message4 {
            get {
                return ResourceManager.GetString("Message4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This department is currently under construction..
        /// </summary>
        internal static string Message5 {
            get {
                return ResourceManager.GetString("Message5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently there is no list of available contract templates.
        /// </summary>
        internal static string Message6 {
            get {
                return ResourceManager.GetString("Message6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently no list of contract number sequences..
        /// </summary>
        internal static string Message7 {
            get {
                return ResourceManager.GetString("Message7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Month Text).
        /// </summary>
        internal static string MonthText {
            get {
                return ResourceManager.GetString("MonthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Company.
        /// </summary>
        internal static string MyCompany {
            get {
                return ResourceManager.GetString("MyCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name  Of  Bank.
        /// </summary>
        internal static string NameOfBank {
            get {
                return ResourceManager.GetString("NameOfBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name  Of  Contract  Template.
        /// </summary>
        internal static string NameOfContactTemplate {
            get {
                return ResourceManager.GetString("NameOfContactTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name  Of  Service  Type.
        /// </summary>
        internal static string NameOfServiceType {
            get {
                return ResourceManager.GetString("NameOfServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name of the contract signatory.
        /// </summary>
        internal static string NameOfSignator {
            get {
                return ResourceManager.GetString("NameOfSignator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night View.
        /// </summary>
        internal static string NightView {
            get {
                return ResourceManager.GetString("NightView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet.
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Contract.
        /// </summary>
        internal static string NotificationMessage {
            get {
                return ResourceManager.GetString("NotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract has been approved.
        /// </summary>
        internal static string NotificationMessage1 {
            get {
                return ResourceManager.GetString("NotificationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        internal static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not ready yet this feature!.
        /// </summary>
        internal static string NotReadyYet {
            get {
                return ResourceManager.GetString("NotReadyYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported.
        /// </summary>
        internal static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        internal static string Offer {
            get {
                return ResourceManager.GetString("Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer And Objection.
        /// </summary>
        internal static string OfferAndObjection {
            get {
                return ResourceManager.GetString("OfferAndObjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password..
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a complex password that is comfortable for you and remember it. This password is required when logging in..
        /// </summary>
        internal static string PasswordDescription {
            get {
                return ResourceManager.GetString("PasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Cabinet.
        /// </summary>
        internal static string PersonalCabinet {
            get {
                return ResourceManager.GetString("PersonalCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Of Company.
        /// </summary>
        internal static string PhoneNumberOfCompany {
            get {
                return ResourceManager.GetString("PhoneNumberOfCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        internal static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the new password..
        /// </summary>
        internal static string PleaseCheckNewPassword {
            get {
                return ResourceManager.GetString("PleaseCheckNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Service Info.
        /// </summary>
        internal static string PleaseEnterServiceInfo {
            get {
                return ResourceManager.GetString("PleaseEnterServiceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position of the signatory of the agreement.
        /// </summary>
        internal static string PositionOfSignator {
            get {
                return ResourceManager.GetString("PositionOfSignator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparer.
        /// </summary>
        internal static string Preparer {
            get {
                return ResourceManager.GetString("Preparer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press The Button.
        /// </summary>
        internal static string PressTheButton {
            get {
                return ResourceManager.GetString("PressTheButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit And Loss.
        /// </summary>
        internal static string ProfitAndLoss {
            get {
                return ResourceManager.GetString("ProfitAndLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposals And Objections.
        /// </summary>
        internal static string ProposalsAndObjections {
            get {
                return ResourceManager.GetString("ProposalsAndObjections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose Of Contract.
        /// </summary>
        internal static string PurposeOfContract {
            get {
                return ResourceManager.GetString("PurposeOfContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Code.
        /// </summary>
        internal static string QQS_Code {
            get {
                return ResourceManager.GetString("QQS_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the details of the client (executor) remain open?.
        /// </summary>
        internal static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you searching from the list of saved clients?.
        /// </summary>
        internal static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter customer (contractor) details.
        /// </summary>
        internal static string Question3 {
            get {
                return ResourceManager.GetString("Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is accountant provided?.
        /// </summary>
        internal static string Question4 {
            get {
                return ResourceManager.GetString("Question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is legal counsel provided?.
        /// </summary>
        internal static string Question5 {
            get {
                return ResourceManager.GetString("Question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there an excise tax?.
        /// </summary>
        internal static string Question6 {
            get {
                return ResourceManager.GetString("Question6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you agree with the public offer?.
        /// </summary>
        internal static string Question7 {
            get {
                return ResourceManager.GetString("Question7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter your new password.
        /// </summary>
        internal static string RepeatNewPassword {
            get {
                return ResourceManager.GetString("RepeatNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID va Parolni saqlash.
        /// </summary>
        internal static string SaveIDAndPassword {
            get {
                return ResourceManager.GetString("SaveIDAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select digital signature key.
        /// </summary>
        internal static string Select_ERI_Key {
            get {
                return ResourceManager.GetString("Select_ERI_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select company.
        /// </summary>
        internal static string SelectClientCompany {
            get {
                return ResourceManager.GetString("SelectClientCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select currency.
        /// </summary>
        internal static string SelectCurrency {
            get {
                return ResourceManager.GetString("SelectCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select default template.
        /// </summary>
        internal static string SelectDefaultTemplate {
            get {
                return ResourceManager.GetString("SelectDefaultTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select format.
        /// </summary>
        internal static string SelectFormat {
            get {
                return ResourceManager.GetString("SelectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select measure.
        /// </summary>
        internal static string SelectMeasure {
            get {
                return ResourceManager.GetString("SelectMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the position.
        /// </summary>
        internal static string SelectPosition {
            get {
                return ResourceManager.GetString("SelectPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the VAT.
        /// </summary>
        internal static string SelectQQS {
            get {
                return ResourceManager.GetString("SelectQQS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify a service type template.
        /// </summary>
        internal static string SelectServiceType {
            get {
                return ResourceManager.GetString("SelectServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select service type.
        /// </summary>
        internal static string SelectServiceTypeTitle {
            get {
                return ResourceManager.GetString("SelectServiceTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send code again.
        /// </summary>
        internal static string SendAgain {
            get {
                return ResourceManager.GetString("SendAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a special code sent to the phone number you specified via the Telegram network..
        /// </summary>
        internal static string SendCodeByTelegram {
            get {
                return ResourceManager.GetString("SendCodeByTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send contract.
        /// </summary>
        internal static string SendContract {
            get {
                return ResourceManager.GetString("SendContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send code again.
        /// </summary>
        internal static string SendSpecialCode {
            get {
                return ResourceManager.GetString("SendSpecialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred on the server, please wait!.
        /// </summary>
        internal static string ServerMessage1 {
            get {
                return ResourceManager.GetString("ServerMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to exit?.
        /// </summary>
        internal static string SignOutText {
            get {
                return ResourceManager.GetString("SignOutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the phone number..
        /// </summary>
        internal static string SignUp_Message_1 {
            get {
                return ResourceManager.GetString("SignUp_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password..
        /// </summary>
        internal static string SignUp_Message_2 {
            get {
                return ResourceManager.GetString("SignUp_Message_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the password..
        /// </summary>
        internal static string SignUp_Message_3 {
            get {
                return ResourceManager.GetString("SignUp_Message_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully registered.
        /// </summary>
        internal static string SignUp_Message_4 {
            get {
                return ResourceManager.GetString("SignUp_Message_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will send you a special code via telegram network. Therefore, the phone number must be connected to the Telegram network.
        /// </summary>
        internal static string SignUpDescription {
            get {
                return ResourceManager.GetString("SignUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone number.
        /// </summary>
        internal static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign window.
        /// </summary>
        internal static string SignWindow {
            get {
                return ResourceManager.GetString("SignWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You missed the waiting time. Please click the Resend Code button.
        /// </summary>
        internal static string SkippedTimeText {
            get {
                return ResourceManager.GetString("SkippedTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a special code sent to the phone number you specified via the Telegram network..
        /// </summary>
        internal static string SpecialCodeDescription {
            get {
                return ResourceManager.GetString("SpecialCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Part.
        /// </summary>
        internal static string SpecialPart {
            get {
                return ResourceManager.GetString("SpecialPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIN.
        /// </summary>
        internal static string STIR {
            get {
                return ResourceManager.GetString("STIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added.
        /// </summary>
        internal static string SuccessfullyAdded {
            get {
                return ResourceManager.GetString("SuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Completed..
        /// </summary>
        internal static string SuccessfullyCompleted {
            get {
                return ResourceManager.GetString("SuccessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated.
        /// </summary>
        internal static string SuccessfullyUpdated {
            get {
                return ResourceManager.GetString("SuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a picture.
        /// </summary>
        internal static string TakePicture {
            get {
                return ResourceManager.GetString("TakePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination Of Contract.
        /// </summary>
        internal static string TerminationOfContract {
            get {
                return ResourceManager.GetString("TerminationOfContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Make Contract.
        /// </summary>
        internal static string ToMakeContract {
            get {
                return ResourceManager.GetString("ToMakeContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Register.
        /// </summary>
        internal static string ToRegister {
            get {
                return ResourceManager.GetString("ToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Cost Of The Service:.
        /// </summary>
        internal static string TotalCostOfTheService {
            get {
                return ResourceManager.GetString("TotalCostOfTheService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type currency.
        /// </summary>
        internal static string TypeCurrency {
            get {
                return ResourceManager.GetString("TypeCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type measure.
        /// </summary>
        internal static string TypeMeasure {
            get {
                return ResourceManager.GetString("TypeMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unapproved.
        /// </summary>
        internal static string Unapproved {
            get {
                return ResourceManager.GetString("Unapproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unapproved Contracts.
        /// </summary>
        internal static string UnapprovedContracts {
            get {
                return ResourceManager.GetString("UnapprovedContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unapproved Contracts.
        /// </summary>
        internal static string UnapprovedContracts1 {
            get {
                return ResourceManager.GetString("UnapprovedContracts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unapproved 
        ///Contracts.
        /// </summary>
        internal static string UnapprovedContracts2 {
            get {
                return ResourceManager.GetString("UnapprovedContracts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Of  Measure.
        /// </summary>
        internal static string UnitOfMeasure {
            get {
                return ResourceManager.GetString("UnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification by digital signature key.
        /// </summary>
        internal static string VerificationBy_ERI_Key {
            get {
                return ResourceManager.GetString("VerificationBy_ERI_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of the app.
        /// </summary>
        internal static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sound.
        /// </summary>
        internal static string Voice {
            get {
                return ResourceManager.GetString("Voice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Time.
        /// </summary>
        internal static string WaitingTime {
            get {
                return ResourceManager.GetString("WaitingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save the changes?.
        /// </summary>
        internal static string WouldYouLikeToSave {
            get {
                return ResourceManager.GetString("WouldYouLikeToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong current password..
        /// </summary>
        internal static string WrongCurrentPassword {
            get {
                return ResourceManager.GetString("WrongCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong service price..
        /// </summary>
        internal static string WrongServicePrice {
            get {
                return ResourceManager.GetString("WrongServicePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X - .
        /// </summary>
        internal static string X1 {
            get {
                return ResourceManager.GetString("X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential numbering system.
        /// </summary>
        internal static string XText1 {
            get {
                return ResourceManager.GetString("XText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Contains at least three cells).
        /// </summary>
        internal static string XText2 {
            get {
                return ResourceManager.GetString("XText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This identification mark must be present.
        /// </summary>
        internal static string XText3 {
            get {
                return ResourceManager.GetString("XText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y - .
        /// </summary>
        internal static string Y1 {
            get {
                return ResourceManager.GetString("Y1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Contains at least two or four cells).
        /// </summary>
        internal static string YearText {
            get {
                return ResourceManager.GetString("YearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your choose.
        /// </summary>
        internal static string YourChoose {
            get {
                return ResourceManager.GetString("YourChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ID number.
        /// </summary>
        internal static string YourIdNumber {
            get {
                return ResourceManager.GetString("YourIdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your signature.
        /// </summary>
        internal static string YourSignature {
            get {
                return ResourceManager.GetString("YourSignature", resourceCulture);
            }
        }
    }
}
