//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contract.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dasturiy ta&apos;minot haqida.
        /// </summary>
        internal static string AboutSoftware {
            get {
                return ResourceManager.GetString("AboutSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xisob raqami.
        /// </summary>
        internal static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korxona manzili.
        /// </summary>
        internal static string AddressOfCompany {
            get {
                return ResourceManager.GetString("AddressOfCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shartnomalar.
        /// </summary>
        internal static string AllContracts {
            get {
                return ResourceManager.GetString("AllContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amaldagi shartnomalar.
        /// </summary>
        internal static string ApplicableContracts1 {
            get {
                return ResourceManager.GetString("ApplicableContracts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amaldagi 
        ///shartnomalar.
        /// </summary>
        internal static string ApplicableContracts2 {
            get {
                return ResourceManager.GetString("ApplicableContracts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shartnoma maker.
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siz QQS to&apos;lovchimisiz?.
        /// </summary>
        internal static string AreYou_QQS_Payer {
            get {
                return ResourceManager.GetString("AreYou_QQS_Payer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank kodi.
        /// </summary>
        internal static string BankCode {
            get {
                return ResourceManager.GetString("BankCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yakunlash.
        /// </summary>
        internal static string ButtonFinished {
            get {
                return ResourceManager.GetString("ButtonFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyingisi.
        /// </summary>
        internal static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekor qilingan shartnomalar.
        /// </summary>
        internal static string CanceledContracts {
            get {
                return ResourceManager.GetString("CanceledContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosh hisobchi F.I.O.
        /// </summary>
        internal static string ChiefAccountantName {
            get {
                return ResourceManager.GetString("ChiefAccountantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korxona logotipi.
        /// </summary>
        internal static string CompanyLogo {
            get {
                return ResourceManager.GetString("CompanyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korxona nomi.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabriklaymiz!.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Davom ettirish .
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shartnoma raqam ketma-ketligi.
        /// </summary>
        internal static string ContractNumberSequence {
            get {
                return ResourceManager.GetString("ContractNumberSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shartnoma shablonlari.
        /// </summary>
        internal static string ContractTemplates {
            get {
                return ResourceManager.GetString("ContractTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shartnoma tuzish.
        /// </summary>
        internal static string CreateContract {
            get {
                return ResourceManager.GetString("CreateContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shartnoma raqamini yaratish.
        /// </summary>
        internal static string CreateContractNumber {
            get {
                return ResourceManager.GetString("CreateContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shartnoma shablonini yaratish.
        /// </summary>
        internal static string CreatingContractTemplate {
            get {
                return ResourceManager.GetString("CreatingContractTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korxona CTIRi.
        /// </summary>
        internal static string CTRiOfCompany {
            get {
                return ResourceManager.GetString("CTRiOfCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijozlar.
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akkaunt parolini tahrirlash.
        /// </summary>
        internal static string EditAccountPassword {
            get {
                return ResourceManager.GetString("EditAccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rekvizit ma&apos;lumotlarini tahrirlash.
        /// </summary>
        internal static string EditRequisiteInformation {
            get {
                return ResourceManager.GetString("EditRequisiteInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korxona manzilini kiriting.
        /// </summary>
        internal static string EnterAddressOfCompany {
            get {
                return ResourceManager.GetString("EnterAddressOfCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank kodini kiriting.
        /// </summary>
        internal static string EnterBankCode {
            get {
                return ResourceManager.GetString("EnterBankCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korxona nomini kiriting.
        /// </summary>
        internal static string EnterCompanyName {
            get {
                return ResourceManager.GetString("EnterCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank nomini kiriting.
        /// </summary>
        internal static string EnterNameOfBank {
            get {
                return ResourceManager.GetString("EnterNameOfBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaxsiy parolni kiriting.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaxsiy parolni qayta kiriting.
        /// </summary>
        internal static string EnterPasswordAgain {
            get {
                return ResourceManager.GetString("EnterPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxsus kodni kiriting.
        /// </summary>
        internal static string EnterSpecialCode {
            get {
                return ResourceManager.GetString("EnterSpecialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rekvizit ma&apos;lumotlar to&apos;g&apos;irligiga e&apos;tibor bering. Ushbu ma&apos;lumotlar shartnoma tuzish vaqtida korxona rekviziti sifatida foydalaniladi.
        /// </summary>
        internal static string FillInfoDescription {
            get {
                return ResourceManager.GetString("FillInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iltimos, korxonangizning rekvizitlarini kiriting..
        /// </summary>
        internal static string FillInfoTitle {
            get {
                return ResourceManager.GetString("FillInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.I.O.
        /// </summary>
        internal static string FistAndLastName {
            get {
                return ResourceManager.GetString("FistAndLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID raqamingiz.
        /// </summary>
        internal static string IDNumber {
            get {
                return ResourceManager.GetString("IDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISTALGAN JOYDA 
        /// SHARTNOMA TUZISH.
        /// </summary>
        internal static string Intro1_1 {
            get {
                return ResourceManager.GetString("Intro1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofisda bo&apos;lmang, bug&apos;galterni kutmang.  
        ///O&apos;zingizga qulay vaqtda, qulay joyda 
        ///shartnomalarni tuzing..
        /// </summary>
        internal static string Intro1_2 {
            get {
                return ResourceManager.GetString("Intro1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAYYOR SHARTNOMANI ONSON 
        /// JO&apos;NATISH.
        /// </summary>
        internal static string Intro2_1 {
            get {
                return ResourceManager.GetString("Intro2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shartnomalarni qo&apos;lda olib borish 
        /// shart emas. Ularni istalgan messenjer 
        /// orqali PDF formatida yuvorish..
        /// </summary>
        internal static string Intro2_2 {
            get {
                return ResourceManager.GetString("Intro2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QISQA MUDDATDA 
        /// SHARTNOMA TUZISH.
        /// </summary>
        internal static string Intro3_1 {
            get {
                return ResourceManager.GetString("Intro3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endi shartnoma tuzish ko&apos;p vaqt olmaydi. 
        /// Shunchaki asosiy ma&apos;lumotlarni 
        /// to&apos;ldiring va shartnoma tayyor..
        /// </summary>
        internal static string Intro3_2 {
            get {
                return ResourceManager.GetString("Intro3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QULAY SHABLONLAR 
        /// YARATISH.
        /// </summary>
        internal static string Intro4_1 {
            get {
                return ResourceManager.GetString("Intro4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shartnoma tuzish uchu o&apos;z huquqlar, 
        /// talablar va imidjingizga mos 
        /// shablonlarni yaratib, 
        /// ulardan onson foydalaning..
        /// </summary>
        internal static string Intro4_2 {
            get {
                return ResourceManager.GetString("Intro4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hisobchi ko&apos;zda tutilganmi?.
        /// </summary>
        internal static string IsCounterProvided {
            get {
                return ResourceManager.GetString("IsCounterProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yurist konsultant ko&apos;zda tutilganmi?.
        /// </summary>
        internal static string IsLegalCounselProvided {
            get {
                return ResourceManager.GetString("IsLegalCounselProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yurist konsultant F.I.O.
        /// </summary>
        internal static string LegalConsultantName {
            get {
                return ResourceManager.GetString("LegalConsultantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOYDA VA ZARARLARNI 
        /// TAHLIL QILISH.
        /// </summary>
        internal static string LoginInfo1_1 {
            get {
                return ResourceManager.GetString("LoginInfo1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcha bajarilgan amalyotlar bo&apos;yicha 
        /// kirim-chimlarni foyda va zararlarga 
        /// ajrating.
        /// </summary>
        internal static string LoginInfo1_2 {
            get {
                return ResourceManager.GetString("LoginInfo1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tizimga kirish.
        /// </summary>
        internal static string LoginSystem {
            get {
                return ResourceManager.GetString("LoginSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telfon raqamingizni kiriting.
        /// </summary>
        internal static string M_EnterPhoneNumber {
            get {
                return ResourceManager.GetString("M_EnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoki.
        /// </summary>
        internal static string M_Or {
            get {
                return ResourceManager.GetString("M_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ro&apos;yxatdan o&apos;ting.
        /// </summary>
        internal static string M_SignUp {
            get {
                return ResourceManager.GetString("M_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assalomu alaykum hurmatli mijoz!.
        /// </summary>
        internal static string M_Title1 {
            get {
                return ResourceManager.GetString("M_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tizimdan foydalanish uchun avtorizasiya qiling..
        /// </summary>
        internal static string M_Title2 {
            get {
                return ResourceManager.GetString("M_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayni damda tadiqlanmagan shartnomalar mavjud emas..
        /// </summary>
        internal static string Message1 {
            get {
                return ResourceManager.GetString("Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mening korxonam.
        /// </summary>
        internal static string MyCompany {
            get {
                return ResourceManager.GetString("MyCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank nomi.
        /// </summary>
        internal static string NameOfBank {
            get {
                return ResourceManager.GetString("NameOfBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shartnoma imzolovchining F.I.O.
        /// </summary>
        internal static string NameOfSignator {
            get {
                return ResourceManager.GetString("NameOfSignator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iltimos, o&apos;zingizga qulay bo&apos;lgan murakkab parolni kiriting va unutmang. Bu parol, siz tizimga kirishingiz vaqtida kerak bo&apos;ladi..
        /// </summary>
        internal static string PasswordDescription {
            get {
                return ResourceManager.GetString("PasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shaxsiy kabinet.
        /// </summary>
        internal static string PersonalCabinet {
            get {
                return ResourceManager.GetString("PersonalCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korxona telfon raqami.
        /// </summary>
        internal static string PhoneNumberOfCompany {
            get {
                return ResourceManager.GetString("PhoneNumberOfCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iltimos .
        /// </summary>
        internal static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shartnoma imzolovchinning lavozimi.
        /// </summary>
        internal static string PositionOfSignator {
            get {
                return ResourceManager.GetString("PositionOfSignator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tugmasini bosing.
        /// </summary>
        internal static string PressTheButton {
            get {
                return ResourceManager.GetString("PressTheButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foyda va zarar.
        /// </summary>
        internal static string ProfitAndLoss {
            get {
                return ResourceManager.GetString("ProfitAndLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taklif va e&apos;tirozlar.
        /// </summary>
        internal static string ProposalsAndObjections {
            get {
                return ResourceManager.GetString("ProposalsAndObjections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QQS Raqami.
        /// </summary>
        internal static string QQS_Code {
            get {
                return ResourceManager.GetString("QQS_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodni qayta yuborish.
        /// </summary>
        internal static string SendSpecialCode {
            get {
                return ResourceManager.GetString("SendSpecialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sozlamalar.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tizimdan chiqish.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ro&apos;yxatdan o&apos;tish.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biz sizga telegram tarmog&apos;i orqali maxsus kod yuvoramiz. Shu bois, telfon raqam telegram tarmog&apos;iga ulangan bo&apos;lishi lozim..
        /// </summary>
        internal static string SignUpDescription {
            get {
                return ResourceManager.GetString("SignUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telfon raqamingizni kiriting.
        /// </summary>
        internal static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O&apos;tkazib yuborish.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siz kutish vaqtini o&apos;tkazib yubordingiz. Iltimos kodni qayta yuvorish tugmasini bosing.
        /// </summary>
        internal static string SkippedTimeText {
            get {
                return ResourceManager.GetString("SkippedTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram tarmog&apos;i orqali siz ko&apos;rsatgan telfon raqamiga yuborilgan maxsus kodni kiriting..
        /// </summary>
        internal static string SpecialCodeDescription {
            get {
                return ResourceManager.GetString("SpecialCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to muvaffaqiyatli yakunladingiz..
        /// </summary>
        internal static string SuccessfullyCompleted {
            get {
                return ResourceManager.GetString("SuccessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shablonlar.
        /// </summary>
        internal static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siz ro&apos;yxatdan o&apos;tishni.
        /// </summary>
        internal static string ToRegister {
            get {
                return ResourceManager.GetString("ToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasdiqlanmagan shartnomalar.
        /// </summary>
        internal static string UnconfirmedContracts1 {
            get {
                return ResourceManager.GetString("UnconfirmedContracts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasdiqlanmagan 
        ///shartnomalar.
        /// </summary>
        internal static string UnconfirmedContracts2 {
            get {
                return ResourceManager.GetString("UnconfirmedContracts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kutish vaqti.
        /// </summary>
        internal static string WaitingTime {
            get {
                return ResourceManager.GetString("WaitingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizning ID raqamingiz.
        /// </summary>
        internal static string YourIdNumber {
            get {
                return ResourceManager.GetString("YourIdNumber", resourceCulture);
            }
        }
    }
}
