using Xamarin.Forms;
using Xamarin.Forms.Xaml;

[assembly: XamlCompilation(XamlCompilationOptions.Compile)] 
[assembly: ExportFont("Nunito_Black.ttf", Alias = "Nunito_Black")]
[assembly: ExportFont("Nunito_BlackItalic.ttf", Alias = "Nunito_BlackItalic")]
[assembly: ExportFont("Nunito_Bold.ttf", Alias = "Nunito_Bold")]
[assembly: ExportFont("Nunito_BoldItalic.ttf", Alias = "Nunito_BoldItalic")]
[assembly: ExportFont("Nunito_ExtraBold.ttf", Alias = "Nunito_ExtraBold")]
[assembly: ExportFont("Nunito_ExtraBoldItalic.ttf", Alias = "Nunito_ExtraBoldItalic")]
[assembly: ExportFont("Nunito_ExtraLight.ttf", Alias = "Nunito_ExtraLight")]
[assembly: ExportFont("Nunito_ExtraLightItalic.ttf", Alias = "Nunito_ExtraLightItalic")]
[assembly: ExportFont("Nunito_Italic.ttf", Alias = "Nunito_Italic")]
[assembly: ExportFont("Nunito_Light.ttf", Alias = "Nunito_Light")]
[assembly: ExportFont("Nunito_LightItalic.ttf", Alias = "Nunito_LightItalic")]
[assembly: ExportFont("Nunito_Medium.ttf", Alias = "Nunito_Medium")]
[assembly: ExportFont("Nunito_MediumItalic.ttf", Alias = "Nunito_MediumItalic")]
[assembly: ExportFont("Nunito_Regular.ttf", Alias = "Nunito_Regular")]
[assembly: ExportFont("Nunito_SemiBold.ttf", Alias = "Nunito_SemiBold")]
[assembly: ExportFont("Nunito_SemiBoldItalic.ttf", Alias = "Nunito_SemiBoldItalic")]